apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
type: Opaque
data:
  db-url: {{ .Values.secret.dbUrl | b64enc }}
  db-user: {{ .Values.secret.dbUser | b64enc }}
  db-password: {{ .Values.secret.dbPassword | b64enc }}
  security-password: {{ .Values.secret.securityPassword | b64enc }}