name: CD-DEV

on:
  repository_dispatch:
    types: [deploy-dev]
  push:                    # ← añade esto para pruebas
    branches:
      - develop    
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev 

    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3

      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

          
      - name: Deploy with Helm
        run: |

            helm upgrade --install backend-mgt-app ./backend-mgt-app \
            --namespace dev \
            --create-namespace \
            -f backend-mgt-app/values-dev.yaml \
            --set image.tag=${{ github.event.client_payload.image }} \
            --set datasource.password=${{ secrets.DB_PASSWORD }}