name: CD-DEV

on:
  repository_dispatch:
    types: [deploy-dev]
  push:                    # ← añade esto para pruebas
    branches:
      - develop    
    

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
   

    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v4

      - name: Set Kubeconfig
        run: |
         mkdir -p ~/.kube
         printf '%s' "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy with Helm
        env:
           KUBECONFIG: /home/hakim/.kube/config
        run: |
           helm upgrade --install backend-mgt-app . \
           --namespace dev \
           --create-namespace \
            -f values.yaml \
           --set image.tag=${{ github.event.client_payload.image }} \
           --set secret.dbPassword=${{ secrets.DB_PASSWORD }}